version: "3"
services:
  xcuitest:
    image: xcuitest:0.0.1
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    entrypoint: bash -c "sleep 30 && saucectl run -c /opt/xcuitest.yaml"
    volumes: 
      - ./containers/xcuitest-saucectl/xcuitest.yaml:/opt/xcuitest.yaml
    depends_on:
      - sauce-connect

  sauce-connect:
    image: "saucelabs/sauce-connect:5.0.1"
    environment:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
    entrypoint: "sc run -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -c /opt/sauce-connect.yaml"
    network_mode: host
    volumes: 
      - ./sauce-connect.yaml:/opt/sauce-connect.yaml

  node-server:
    image: node-server:0.0.1
    network_mode: host
    entrypoint: "node /opt/app.js"
