apiVersion: v1alpha
kind: imagerunner
sauce:
  region: us-west-1
suites:
- name: xcuitest
  image: sminch/xcuitest:0.0.8
  workload: webdriver
  entrypoint: bash -c "sleep 30 && saucectl run -c /opt/xcuitest.yaml"
  env:
    SAUCE_USERNAME: ${SAUCE_USERNAME}
    SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
    SAUCE_OUTPUT_FORMAT: "text"

  services:
  - name: sauce-connect
    image: saucelabs/sauce-connect:5.0.1
    entrypoint: "sc run -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -c sauce-connect.yaml"
    env:
      SAUCE_USERNAME: ${SAUCE_USERNAME}
      SAUCE_ACCESS_KEY: ${SAUCE_ACCESS_KEY}
      SAUCE_OUTPUT_FORMAT: "text"
      SAUCE_CONFIG_FILE: "/sauce-connect.yaml"
    files:
        - src: "./sauce-connect.yaml"
          dst: "/sauce-connect.yaml"
  - name: node-server
    image: sminch/node-server:0.0.1
    network_mode: host
    entrypoint: "node /opt/app.js"
