apiVersion: v1alpha
kind: xcuitest
sauce:
  tunnel:
    name: xcuitest-so-tunnel
    timeout: "2m"
  region: us-west-1
  concurrency: 20
  metadata:
    build: XCUITest Simulator on Sauce Orchestrate
xcuitest:
  app: storage:filename=WebKitBrowser.zip
  testApp: storage:filename=WebKitBrowserUITests-Runner.zip

suites:
  - name: "WebKitBrowser to Localhost"
    simulators:
      - name: "iPhone 14 Simulator"
        orientation: portrait
        platformVersions:
          - "16.2"

artifacts:
  download:
    when: always
    match:
      - "junit.xml"
    directory: ./artifacts/
